version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: recipe-manager-db
    environment:
      POSTGRES_DB: recipe_manager
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recipe_user -d recipe_manager"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
